### ISSUE TITLE
AddServiceActivator isn't available

### ISSUE THREAD

**Issue by blastdan** [BrighterCommand/Paramore.Brighter.Extensions#13]
I can't seem to get the AddServiceActivator to work. It also doesn't appear as though the code is found in the binary. The object browser doesn't show it available to me.

Am I doing something wrong?

![image](https://user-images.githubusercontent.com/2110769/45230398-b4070e80-b296-11e8-8016-84cd20e10575.png)

```C#
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Paramore.Brighter.AspNetCore;
using Paramore.Brighter.MessagingGateway.RMQ;
using Swashbuckle.AspNetCore.Swagger;
```

```C#
// Found!
services.AddBrighter()
 .HandlersFromAssemblies(typeof(GreetingCommandHandler).Assembly);

 // Not Found!!!
 services.AddServiceActivator(options =>
              {
                options.Connections = connections;
                options.ChannelFactory = new InputChannelFactory(rmqMessageConsumerFactory);
               })
               .MapperRegistryFromAssemblies(typeof(GreetingCommandHandler).Assembly)
               .HandlersFromAssemblies(typeof(GreetingCommandHandler).Assembly);
```

**Comment by holytshirt** [comment]
Hi @blastdan, I've completely rewritten the code and looking to re-release under new nuget packages hopefully today or tomorrow.
The code on  master has not been released yet.

**Comment by holytshirt** [comment]
I've update and released:
DependencyInjection extension for Brigther https://www.nuget.org/packages/Paramore.Brighter.Extensions.DependencyInjection/
DependencyInjection extension for ServiceActivator https://www.nuget.org/packages/Paramore.Brighter.ServiceActivator.Extensions.DependencyInjection/
and (IHostBuilder) support for background tasks https://www.nuget.org/packages/Paramore.Brighter.ServiceActivator.Extensions.Hosting/

https://github.com/BrighterCommand/Paramore.Brighter.Extensions

It's was originally Paramore.Brighter.AspNetCore but but have renamed it as it does not make sense anymore as it is not just for aspnetcore anymore.
Will redirected the older package soon

Try them out and logs those bugs and feed back please!
