### ISSUE TITLE
Move Paramore Brighter Extensions within the Brighter repo

### ISSUE THREAD

**Issue by iancooper** [BrighterCommand/Paramore.Brighter.Extensions#54]
Whilst we once considered DI outside of our boundary, relying on the factory model, it's clear that whilst the design brings many benefits, a **lot** of our customers will just use the IoC container support built into HostService.

Indeed, we have always know that configuration of Brighter is one of its 'pain' points. We get a lot for the work you have to do (simple handler model etc.) but you have to write a fair amount of boilerplate.

Working with HostBuilder, and defaults around how we configure Brighter helps adoption. 

So whilst I don't want to change Brighter's architecture, I would like to include this within the core Brighter repo. I think it is a core part of our offering now,  not just an add on.

**Comment by holytshirt** [comment]
Almost done
