### ISSUE TITLE
Is there going to be version 1.0.0?

### ISSUE THREAD

**Issue by mrmartan** [BrighterCommand/Paramore.Brighter.Extensions#6]
I am currently considering to use Brighter and looking into integrating it with ASP.NET Core 2.0 and came over this library. So as the title asks will there be a version 1.0.0?

If I am to do this integration myself and take inspiration from this project, I have a question about https://github.com/dstockhammer/Paramore.Brighter.AspNetCore/commit/d0736a18c28c67259ea90b9d1bd2108c19f4ae00 

Why are you building the service provider every time rather than accepting IServiceProvider instead of IServiceCollection?

**Comment by dstockhammer** [comment]
Sorry for the ultra late reply! Yeah, I think there has been enough feedback to justify bumping to v1.

As for your question, it's requiring `IServiceCollection` because in `ConfigureServices` the service provider is not yet available. It then builds the service provider every call, because otherwise it can't handle scopes correctly. That was the bug fixed in the commit you referenced.

**Comment by mrmartan** [comment]
I would agrue you are using IServiceCollection wrong and this is why it provides deffered execution so that I can define dependencies in `ConfigureServices` even though service provider is not yet ready.

Look at
```csharp
 IServiceCollection AddScoped<TService>(this IServiceCollection services, Func<IServiceProvider, TService> implementationFactory) where TService : class
```
There is your service provider.
I would also argue that the service factory is the wrong place to handle scoping. The factory itself could be a scoped service.

I can't really say this all is applicable to you, but building the container on every call is really bad.

**Comment by Cyberkruz** [comment]
When looking into it I think it can be fixed by having the AspNetHandlerFactory bring in a IServiceProvider instead of a IServiceCollection like so:

```
public class AspNetHandlerFactory : 
        IAmAHandlerFactory, IAmAHandlerFactoryAsync
    {
        private readonly IServiceProvider _services;

        public AspNetHandlerFactory(IServiceProvider services)
        {
            _services = services;
        }

        IHandleRequests IAmAHandlerFactory.Create(Type handlerType)
        {
            return (IHandleRequests)_services.GetService(handlerType);
        }

        IHandleRequestsAsync IAmAHandlerFactoryAsync.Create(Type handlerType)
        {
            return (IHandleRequestsAsync)_services.GetService(handlerType);
        }

        public void Release(IHandleRequests handler)
        {
            // no op
        }

        public void Release(IHandleRequestsAsync handler)
        {
            // no op
        }
    }
```

Then you'd update the AddBrighter method to use the IServiceProvider function overload when registering it. @mrmartan Is this more in line with what you were thinking? That way the container isn't built every call. (The code is a bit sloppy. For demo purpose only).

```
public static IBrighterHandlerBuilder AddBrighter(
            this IServiceCollection services, 
            Action<BrighterOptions> configure = null)
        {
            if (services == null)
                throw new ArgumentNullException(nameof(services));

            var options = new BrighterOptions();
            configure?.Invoke(options);

            var subscriberRegistry = new AspNetSubscriberRegistry(services, options.HandlerLifetime);

            services.AddSingleton(options);
            services.AddSingleton(subscriberRegistry);
            
            services.AddSingleton<IAmACommandProcessor>(BuildCommandProcessor);

            return new AspNetHandlerBuilder(services, subscriberRegistry);
        }

        private static IAmACommandProcessor BuildCommandProcessor(IServiceProvider provider)
        {
            var options = provider.GetService<BrighterOptions>();
            var subscriberRegistry = provider.GetService<AspNetSubscriberRegistry>();

            var handlerFactory = new AspNetHandlerFactory(provider);
            var handlerConfiguration = new HandlerConfiguration(subscriberRegistry, handlerFactory, handlerFactory);

            var policyBuilder = CommandProcessorBuilder.With()
                .Handlers(handlerConfiguration);

            var messagingBuilder = options.PolicyRegistry == null
                ? policyBuilder.DefaultPolicy()
                : policyBuilder.Policies(options.PolicyRegistry);

            var builder = options.MessagingConfiguration == null
                ? messagingBuilder.NoTaskQueues()
                : messagingBuilder.TaskQueues(options.MessagingConfiguration);

            var commandProcessor = builder
                .RequestContextFactory(options.RequestContextFactory)
                .Build();

            return commandProcessor;
        }
``

**Comment by Cyberkruz** [comment]
Darker suffers from this problem as well. https://github.com/BrighterCommand/Darker/blob/master/src/Paramore.Darker.AspNetCore/AspNetHandlerFactory.cs

**Comment by holytshirt** [comment]
Hi all, thanks for the ideas. I'm working on updating the code now.
I'm also adding a `IServiceCollection` extension for Service Activator which will use the `Brighter` extension code.
And also adding a `IHostedService` extension
I also would like to rename the packages to naming that is more in line with what others are doing.

So `Paramore.Brighter.AspNetCore` will become `Paramore.Brighter.Extensions.DependencyInjection`
and 2 extra packages if you use them
`Paramore.Brighter.ServiceActivator.Extensions.DependencyInjection`
`Paramore.Brighter.ServiceActivator.Extensions.Hosting`

This all currently on a branch called ServiceHost. 

Also would like to rename the repo to `Paramore.Brighter.Extensions`

I just wanted to say thanks again for your ideas! @mrmartan @Cyberkruz

**Comment by holytshirt** [comment]
Hi everyone 

I've update and released:
DependencyInjection extension for Brigther https://www.nuget.org/packages/Paramore.Brighter.Extensions.DependencyInjection/
DependencyInjection extension for ServiceActivator https://www.nuget.org/packages/Paramore.Brighter.ServiceActivator.Extensions.DependencyInjection/
and (IHostBuilder) support for background tasks https://www.nuget.org/packages/Paramore.Brighter.ServiceActivator.Extensions.Hosting/

https://github.com/BrighterCommand/Paramore.Brighter.Extensions

It's was originally Paramore.Brighter.AspNetCore but but have renamed it as it does not make sense anymore as it is not just for aspnetcore anymore.
Will redirected the older package soon

Try them out and logs those bugs and feed back please!

**Comment by holytshirt** [comment]
Close this issue, as we have released v1 now
